version: '3.8'

services:
  calendar_service:
    image: calendar_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - calendar_data:/usr/src/app
    ports:
      - "5000:5000"
    restart: always

volumes:
  calendar_data: